### ISSUE TITLE
Issue with VideoConverter

### ISSUE THREAD

**Issue by bernardo7894** [sheharyaar/SLAM-Reboot#6]
Getting this while trying to import any YouTube video, with any file name

--------------------29/03/2023 22:04:44 UTC--------------------
NReco.VideoConverter.FFMpegException: D:\Users\Bernardo\Documents\SLAM-v2-01\SLAM-v2-01\lagnos\sT.mp4: No such file or directory (exit code: 1)
   at NReco.VideoConverter.FFMpegConverter.Invoke(String ffmpegArgs)
   at SLAM.Form1.FFMPEG_WaveCreator(String File, String outputFile, SourceGame Game) in C:\Users\sheha\Documents\GitHub\SLAM-Reboot\SLAM\Form1.vb:line 161
   at SLAM.Form1.WavWorker_DoWork(Object sender, DoWorkEventArgs e) in C:\Users\sheha\Documents\GitHub\SLAM-Reboot\SLAM\Form1.vb:line 230

**Comment by bernardo7894** [comment]
I fixed it by updating yt-dlp (`yt-dlp -U`)
